import { Inter } from 'next/font/google'
import {Card,Container,Typography }from '@mui/material';
import { ThemeProvider, CssBaseline } from '@mui/material';
import theme from './style/theme'
import ThemeRegistry from './style/ThemeRegistry';
const inter = Inter({ subsets: ['latin'] })
import Navbar from './../component/Navbar'
import './style/globals.css'
import Footer from '@/component/Footer';
import { Roboto,Poppins } from 'next/font/google'

const roboto = Poppins({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <ThemeRegistry options={{ key: 'mui' }}>
    <html lang="en" className={roboto.className}>
    <body >
    <Container maxWidth='xl' >
           <Navbar/>
          {children}
          <Footer/>
          </Container>
          </body>
          </html>   
          </ThemeRegistry>
  )
}
